[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
switchboard_generate_number = "5p3k3TUCfwYof4HLVsjDgLcWv21YxkPccHMJCXX4AEA2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/siddi_404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
